import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Chess } from "chess.js";
import { supabase } from "../supabase";
import "../styles/feature.css";

export default function PvP(){
 const [user,setUser]=useState(null),[room,setRoom]=useState(null),[code,setCode]=useState(""),[joinCode,setJoinCode]=useState(""),[status,setStatus]=useState(""),[fen,setFen]=useState(new Chess().fen()),[color,setColor]=useState(null),[selected,setSelected]=useState(null),[game,setGame]=useState(()=>new Chess());
 const [channel,setChannel]=useState(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user))},[]);
 useEffect(()=>{if(!room)return;const ch=supabase.channel(`pvp:${room.code}`,{config:{broadcast:{ack:true}}}).on("broadcast",{event:"state"},({payload})=>{if(payload?.sender===user?.id)return;const g=new Chess();try{g.load(payload.fen);setGame(g);setFen(payload.fen);setStatus(payload?.move ? `상대 수: ${payload.move}` : "상대가 움직였습니다.")}catch{}}).on("broadcast",{event:"join"},({payload})=>{if(payload?.userId!==user?.id)setStatus("상대가 입장했습니다!")}).subscribe(s=>{if(s==="SUBSCRIBED"){ch.send({type:"broadcast",event:"join",payload:{userId:user?.id}})}});setChannel(ch);return()=>{supabase.removeChannel(ch)}},[room?.code,user?.id]);
 const create=async()=>{if(!user){setStatus("로그인 후 이용하세요.");return}const c=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await supabase.from("pvp_rooms").insert({code:c,host_id:user.id,status:"waiting",fen:new Chess().fen()}).select().single();if(error){setStatus(error.message);return}setRoom(data);setCode(c);setColor("w");setStatus(`방 코드 ${c} 를 상대에게 알려주세요.`)};
 const join=async()=>{if(!user)return;const {data,error}=await supabase.from("pvp_rooms").select("*").eq("code",joinCode.trim().toUpperCase()).eq("status","waiting").maybeSingle();if(error||!data){setStatus("대기 중인 방을 찾지 못했습니다.");return}const {data:updated,error:e}=await supabase.from("pvp_rooms").update({guest_id:user.id,status:"playing"}).eq("id",data.id).select().single();if(e){setStatus(e.message);return}setRoom(updated);setCode(updated.code);setColor("b");setStatus("대결 시작! 상대의 수를 기다리세요.")};
 const click=sq=>{if(!room||!color)return;const g=new Chess(game.fen());if(g.turn()!==color)return;if(!selected){const p=g.get(sq);if(p?.color===color)setSelected(sq);return}try{const m=g.move({from:selected,to:sq,promotion:"q"});if(!m){setSelected(null);return}setSelected(null);setGame(g);setFen(g.fen());channel?.send({type:"broadcast",event:"state",payload:{sender:user.id,fen:g.fen(),move:m.san}})}catch{setSelected(null)}};
 const glyphs={w:{p:"♙",n:"♘",b:"♗",r:"♖",q:"♕",k:"♔"},b:{p:"♟",n:"♞",b:"♝",r:"♜",q:"♛",k:"♚"}}; const board=useMemo(()=>{const g=new Chess(fen),out=[];for(let r=8;r>=1;r--)for(let c=0;c<8;c++){const sq=String.fromCharCode(97+c)+r,p=g.get(sq),light=(r+c)%2===0,sel=selected===sq;out.push(<button key={sq} onClick={()=>click(sq)} style={{width:70,height:70,border:sel?"3px solid #5ee7ff":0,fontSize:42,background:light?"#d9c7a5":"#7a5b3c",cursor:"pointer"}}>{p?glyphs[p.color][p.type]:""}</button>)}return out},[fen,selected]);
 return <div className="featurePage"><div className="featureShell"><Link to="/" className="featureSub">← 대국으로</Link><h1 className="featureTitle">🌐 실시간 PvP</h1><p className="featureSub">Supabase Realtime Broadcast로 상대에게 수를 즉시 전달합니다.</p><div className="featureGrid"><div className="featureCard"><h3>방 만들기</h3><button className="featureButton" onClick={create}>새 대결방 만들기</button>{code&&<div className="coinBig" style={{fontSize:24,marginTop:15}}>{code}</div>}</div><div className="featureCard"><h3>방 참가</h3><input className="input" value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="6자리 방 코드"/><button className="featureButton" style={{marginTop:10}} onClick={join}>참가하기</button></div></div>{status&&<div className="notice" style={{marginTop:18}}>{status}</div>}{room&&<div className="featureCard" style={{marginTop:18}}><h3>{room.code} · {color==="w"?"백":"흑"}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(8,70px)",width:560,margin:"20px auto"}}>{board}</div><p className="featureSub">현재 턴: {new Chess(fen).turn()==="w"?"백":"흑"}</p></div>}</div></div>
}
